### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by philiplb** [theplant/cldr#7]
Under what license is this software published?
Currently, there is no license stated and so it is proprietary and we can't use it (indirectly via https://github.com/qor/admin ). :(

**Comment by philiplb** [comment]
Any news about this?

**Comment by idealhack** [comment]
thanks for asking! fixed by https://github.com/theplant/cldr/commit/9f76f7ce4ee8058b01f92739cf0d0cceaeda3cb2
